### ISSUE TITLE
Add: methods/scripts to build singularity container with python environment/packages

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#10]
As an example, we can include the scripts to install scikit-hep or just matplotlib/pandas/mplhep/etc.

**Comment by michmx** [comment]
Great idea! I have been thinking in examples for building containers on the fly. 
So far I have covered Pythia and ROOT, but it is true that we have a whole ecosystem in scikit-hep.

**Comment by amanmdesai** [comment]
Yeah. it should very helpful I believe.

One more expansion -- how about also adding a singularity image that contains a combination of both ROOT as well Python packages -- like showcasing a possibility of such a combination

**Comment by amanmdesai** [comment]
Please let me know which episode shall I include this one

**Comment by amanmdesai** [comment]
The repository where I am developing the Container: https://github.com/amanmdesai/singularity-scikit-hep

**Comment by klieret** [comment]
Pinging @michmx
