### ISSUE TITLE
Suggestion: Add lesson on how to build the image with GitHub/GitLab CI/CD

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#13]
This may be already included in other lessons. But may be it can be added just to highlight that GitHub can be used to build singularity container.

**Comment by michmx** [comment]
Some Information here:
https://github.com/singularityhub/github-ci

**Comment by klieret** [comment]
This would probably be a bonus episode, right? (because it also induces a dependency on our gh CI lesson). That's why I marked it as low prio

**Comment by michmx** [comment]
Yes, the bonus episode is probably a good location for the topic.

**Comment by amanmdesai** [comment]
@michmx @klieret  I was testing a hello-world image with github ci here: https://github.com/amanmdesai/hello-world-singularity

Shall I add this to one of the bonus lessons (I think a bonus lesson will be needed?)

**Comment by klieret** [comment]
Very nice!  I'm not an expert, so leaving this for @michmx to comment!

**Comment by amanmdesai** [comment]
@klieret @michmx 

I have prepared github workflow that should build, test and deploy the singularity image to github packages and allow anyone to download it

The repo is here: https://github.com/amanmdesai/singularity-scikit-hep 

The example is to build scikit-hep ecosystem (currently uses pip3 install).

Regarding testing: I am **yet** to include all python tests. However, numpy test was carried out to check if it prints an array. It is successful. 

This work links the issues: #10, #13, #19 
I should be able to solve #14 soon. 

Moreover the work here may bring some possible updates for #18 (Like we could teach how to pull a singularity image using an example hello-singularity image) -- please let me know if this sounds okay.


Moreover, please let me know if there are any suggestions/possible upgrades regarding https://github.com/amanmdesai/singularity-scikit-hep in the [issues](https://github.com/amanmdesai/singularity-scikit-hep/issues)

Thanks

**Comment by amanmdesai** [comment]
@klieret  Could you please create a new empty episode for me (and also let me know how this is done)?

I can then add all the information related to #10, #13, #14, #18, #19 (perhaps also #9)

we can then think whether to include some information in the main module. 
as stated earlier, the scripts to implement the workflow is now ready.

**Comment by amanmdesai** [comment]
since I aim combine several issues into one, I am removing the prio:low label

**Comment by klieret** [comment]
> Could you please create a new empty episode for me (and also let me know how this is done)?

Oh, you can simply create a new markdown file in `_episodes` (nothing more to it)

**Comment by klieret** [comment]
Michel is quite busy this week, I hope he can also join the discussion next week :)

**Comment by amanmdesai** [comment]
> > Could you please create a new empty episode for me (and also let me know how this is done)?
> 
> Oh, you can simply create a new markdown file in `_episodes` (nothing more to it)

Oh i see. thanks. i will do that then.
