### ISSUE TITLE
HSF CMS analysis uses a docker image, we can include scripts to create such a docker image/singularity image here

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#14]
See e.g., https://hsf-training.github.io/hsf-training-cms-analysis-webpage/setup.html

**Comment by amanmdesai** [comment]
I think the script wont be longer than 5-10 lines (we can simply include within the bonus episode)

**Comment by klieret** [comment]
Sounds good!

**Comment by amanmdesai** [comment]
Just an idea: we could use the **docker** image available on dockerhub and pull it using **singularity** to demonstrate how to pull a docker image using singularity thereby partly answering #9

**Comment by amanmdesai** [comment]
with #62 and information already covered earlier in the lesson, it is possible to add this as an bonus exercise within bonus episode (solution maybe given)

What is your opinion @klieret ?

**Comment by amanmdesai** [comment]
Pulling the cern root image is covered in episode 2.
The same can be used for HSF CMS analysis (using singularity pull commands). 


Hence closing this issue.
