### ISSUE TITLE
Information on how to exit a singularity image 

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#17]
also include steps such that the progress is saved.

**Comment by michmx** [comment]
It is very relevant to explain that exiting a container in Singularity will kill all processes running inside. 

For keeping things running, we need to use instances. I am thinking if we want to include a chapter about instances.

**Comment by amanmdesai** [comment]
In my opinion it would be nice if we include a chapter on instances.

**Comment by amanmdesai** [comment]
Just wanted to ask, for this issue we still need to include something on instances, right or shall I open a new issue for that?
