### ISSUE TITLE
Information on how to share singularity images

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#19]
Just like docker images can be shared via GitHub packages/DockerHub is it possible to share singularity images over the same? or do u need to use a separate website/registry?

**Comment by michmx** [comment]
Singularity Hub was the analog to DockerHub, but it is not available anymore to upload images. 

Now that the Singularity open source has been renamed as Apptainer, they show in the documentation how to use library API registries:
https://apptainer.org/docs/user/main/library_api.html
but handling remote endpoints to push images feels overwhelming for the scope of an introductory module like this one. 

Of course, just an opinion.

**Comment by amanmdesai** [comment]
Is bonus episode a good place to add this information?
