### ISSUE TITLE
Expand the Setup 

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-singularity-webpage#2]
Currently, the Setup just suggests checking if Singularity is installed:
https://github.com/hsf-training/hsf-training-singularity-webpage/blob/gh-pages/setup.md

Information to use Singularity/Apptainer locally can be extended. Particularly relevant for building containers with superuser permissions. 

Some ideas:
https://github.com/apptainer/apptainer/blob/main/INSTALL.md

**Comment by amanmdesai** [comment]
Perhaps we can include installation scripts for Ubuntu and Fedora.

Is it possible to use singularity with Windows/Mac? -- maybe we need to state that in system requirements?

**Comment by michmx** [comment]
We have been preparing setups for Windows and Mac in other workshops. Here we can do similar. I managed to work on Mac via Docker (container in a container) since VirtualBox doesn't work on the Macbook M1 laptops. And for Windows, I think same solution can be provided.
