### ISSUE TITLE
Update Readme badges

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#21]
Currently there is sign up badge for carpentry slack, 

however, we have used hsf curriculum badge (as in https://github.com/hsf-training/hsf-training-matplotlib)

hence a change is required.

**Comment by klieret** [comment]
In general we should overhaul/standardize all of the readmes....

**Comment by amanmdesai** [comment]
Yeah. 
Something like [THIS](https://github.com/klieret/python-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/README.md)  with additional training perspective will look good :)
