### ISSUE TITLE
Add coffee breaks! 

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-singularity-webpage#25]
![image](https://user-images.githubusercontent.com/2147367/186988237-b9b07265-e5fe-4d30-a368-6dfd373001c0.png)

**Comment by amanmdesai** [comment]
As per discussion here, https://github.com/hsf-training/hsf-training-singularity-webpage/issues/8, I tagged this as high prio.

**Comment by klieret** [comment]
Good call @amanmdesai
