### ISSUE TITLE
Episode 4: Figure seems to be missing

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#4]

**Comment by michmx** [comment]
![image](https://user-images.githubusercontent.com/2147367/186987236-2f8f349a-23f1-4573-87c7-46b24b5a9229.png)
This is the figure that it is supposed to be shown 😁 
(From https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0177459)
