### ISSUE TITLE
Add one-paragraph description of what singularity/apptainer is

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-singularity-webpage#45]

**Comment by ManasviGoyal** [comment]
Hi. I would like work on this. Just to clarify, this description needs to be added in the readme, right?

**Comment by klieret** [comment]
No, this needs to go in the website (it's a lesson)

**Comment by ManasviGoyal** [comment]
> No, this needs to go in the website (it's a lesson)

Okay. Sorry, I misunderstood. You mean in the episode 1 lesson (`01-introduction.md`) right?

**Comment by klieret** [comment]
Sorry for not including this information in the issue description, I think this refers to the first paragraph on the top level page (`index.md`):

![image](https://user-images.githubusercontent.com/13602468/193460754-6ba3fa53-c439-48e9-b548-9b530bbf3dfd.png)

**Comment by klieret** [comment]
Which should then also be copied to the readme, actually (sorry, I was mistaken before)

**Comment by ManasviGoyal** [comment]
@klieret please check.
