### ISSUE TITLE
Running as non-root - was: Students should ideally have root

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-singularity-webpage#47]

**Comment by michmx** [comment]
In the setup, there is a link for the quick installation in a Linux system, but I am afraid about students using MacOS or Windows (!) in their laptops. 

A solution that we may try and advertize if no other option is running a VM in the computer with a Linux system (an easy one, like Ubuntu), and installing Singularity/Apptainer there. I tried setting up Apptainer inside a Docker container but didn't work (I didn't have time to debug why, sorry).

**Comment by mambelli** [comment]
If the host has user namespaces enabled and CVMFS we can easily run without root. I tested the tutorial that way with the latest apptainer (singularity) in CVMFS.
User namespaces are a good thing to enable and are easy to enable as root on recent EL7 (CentOS/SL) and enabled by default on EL8. Here is an explanation of what they are: https://www.redhat.com/en/blog/whats-next-containers-user-namespaces.
User namespaces are enabled if `cat /proc/sys/user/max_user_namespaces` returns a number bigger than 0
To enable the needed user namespace root can run:
```
echo 10000 > /proc/sys/user/max_user_namespaces
```
If we know ahead of time where people will be running, I can work w/ the sysadmin to make sure that the hosts have CVMFS and user namespaces enabled.

**Comment by mambelli** [comment]
@michmx @klieret  Episodes are inconsistent about the shell commands, some use backtick:
```
    ```bash
    command
    ```
```
others use tilde and source
```
    ~~~bash
    command
    ~~~
    {: .source}
```
OK to leave it as is? Or any preference on what should be used?

**Comment by klieret** [comment]
Preference for python is definitely the first one, because it works out of the box with `blacken-docs` to standardize the python formatting. I think for bash/source it doesn't matter :)

**Comment by klieret** [comment]
IMO the triple-backticks is the much more common syntax for highlighting code blocks, but I think the triple-tilde is a pandoc-style CSS class injection which might be more general, which is perhaps why it was used here.

**Comment by mambelli** [comment]
I ended up changing all bash code to triple-backticks. I pushed PR #69
