### ISSUE TITLE
Add: Is it possible to add labels like Episode 1, 2, ... in the labels option on github for this repository?

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#5]

**Comment by michmx** [comment]
Pinging @klieret .

**Comment by klieret** [comment]
So in principle both of you can create them manually. You can make this set of labels the default for new repositories, but that wouldn't help here.

I'm looking at https://organizer.gitconsensus.com/#/?id=labels for an easier way to sync labels...

**Comment by klieret** [comment]
Though it seems like it can only do this for _all_ repositories at once, not just a selected view... (I just opened https://github.com/gitconsensus/GithubOrganizer/issues/31)

**Comment by klieret** [comment]
It would probably be easy enough to write something with selenium for this though...

**Comment by klieret** [comment]
There's also this: https://github.com/koji/github-label-manager

Which could probably do this right now. I might try this later/tomorrow :)

**Comment by amanmdesai** [comment]
Thank you @klieret

**Comment by klieret** [comment]
This actually works quite well, once I have the config.
@amanmdesai could you head over to https://github.com/hsf-training/hsf-training-matplotlib/labels
and bring the config for all the labels in the following form?

```js
{
      name: 'Type: Bug Fix',
      color: 'FF8A65',
      description: 'Fix features that are not working',
    },
    {
      name: 'Type: Enhancement',
      color: '64B5F7',
      description: 'Add new features',
    },
```

etc.?

You could either paste this here or add it as a file to https://github.com/hsf-training/maintenance/tree/main/standardize-labels

**Comment by klieret** [comment]
This is actually something I wanted to do since quite some time, so it's nice that we finally figure this out :)

**Comment by klieret** [comment]
If you want, you can also adjust our colors ;)  (https://github.com/koji/github-label-manager/labels is much prettier)

**Comment by amanmdesai** [comment]
Sure I will do this.

**Comment by klieret** [comment]
The only downside of this is that now all the labels that you've already added are gone..... Next time I should probably only add new labels rather than deleting the old ones as well....

**Comment by amanmdesai** [comment]
No, I had not added any labels to the issues I posted so far. I will add the new labels to the issues today.
