### ISSUE TITLE
Move "Bonus episode" at the end of the module

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-singularity-webpage#79]
The "Bonus episode" requires knowledge of CI/CD, and at least for the coming workshop, it will be reviewed a day after.

Let's move the bonus to the bottom so we can clarify to the students that the bonus is optional.

**Comment by klieret** [comment]
I think that's already the case though, right?

**Comment by klieret** [comment]
![image](https://user-images.githubusercontent.com/13602468/209937835-2ffd5bdb-130d-4b7a-bc60-91cb77aab152.png)

**Comment by michmx** [comment]
Sorry, I should have been more specific. Not after PR #68

**Comment by klieret** [comment]
Ah right!
