### ISSUE TITLE
Split the chapter "Building Containers"

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-singularity-webpage#8]
The chapter [Building Containers](https://hsf-training.github.io/hsf-training-singularity-webpage/03-building-containers/index.html) tries to cover the building of containers with both interactive mode and definition files.

The pace feels rushed to cover that much in a single chapter. It can be split in two, explaining more details on each way of building your container.

**Comment by klieret** [comment]
I think this should be done as soon as possible then (maybe leaving fine polishing for afterwards), because every chapter afterwards will have to be renamed (because of the filename based ordering scheme...).
Would also mess up the episode tags
