### ISSUE TITLE
Add "Best practices for build recipes"

### ISSUE THREAD

**Issue by michmx** [hsf-training/hsf-training-singularity-webpage#85]
We must include the best practices for build recipes from Apptainer docs:

* Always install packages, programs, data, and files into operating system locations (e.g. not /home, /tmp , or any other directories that might get commonly binded on).

* Document your container. If your runscript doesn’t supply help, write a %help or %apphelp section. A good container tells the user how to interact with it.

* If you require any special environment variables to be defined, add them to the %environment and %appenv sections of the build recipe.

* Files should always be owned by a system account (UID less than 500).

* Ensure that sensitive files like /etc/passwd, /etc/group, and /etc/shadow do not contain secrets.

* Build production containers from a definition file instead of a sandbox that has been manually changed. This ensures the greatest possibility of reproducibility and mitigates the “black box” effect.

Taken from https://apptainer.org/docs/user/1.0/definition_files.html#best-practices-for-build-recipes

**Comment by klieret** [comment]
We could always just link to that. But I'm wondering where to put it exactly, since there's no "summary" episode.

But perhaps at the bottom of episode 5?

**Comment by mambelli** [comment]
I created a PR w/ building best practices:
https://github.com/hsf-training/hsf-training-singularity-webpage/pull/97

I made the changes in the 2 episodes about container building. I think it's the best place

A summary could repeat all recommendations
