### ISSUE TITLE
Liquid syntax not escaped

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-singularity-webpage#94]
Hi @klieret @michmx, 

Following is the full command which is given in the original epsiode 9 file and this is how we expect to see it on the episode website [episode 9](https://github.com/hsf-training/hsf-training-singularity-webpage/blob/gh-pages/_episodes/09-bonus-episode.md):
       
```code
echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
```

however this is **NOT** the case and instead the following is rendered:

```code
 echo $ | singularity remote login -u $ --password-stdin oras://ghcr.io
 singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
```

meaning that ${{ secrets.GITHUB_TOKEN }}  is **missing**.

Any idea how to solve this?

Thanks.

**Comment by klieret** [comment]
ah, that's probably replaced by liquid, the template engine from Jekyll

**Comment by klieret** [comment]
I'll take a look and fix that. Probably just needs some `{{% raw %}}` tags or something around it

**Comment by klieret** [comment]
Very nice catch! ❤️ ❤️

**Comment by amanmdesai** [comment]
Thanks a lot @klieret for fixing this
